/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const KV_TABLE = "kv_store";

/* Table schema:
CREATE TABLE kv_store (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at Supabase Dashboard

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js";

const client = () => createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from(KV_TABLE).upsert({
        key,
        value
    });
    if (error) {
        throw new Error(error.message);
    }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
    const supabase = client()
    const { data, error } = await supabase.from(KV_TABLE).select("value").eq("key", key).maybeSingle();
    if (error) {
        throw new Error(error.message);
    }
    return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from(KV_TABLE).delete().eq("key", key);
    if (error) {
        throw new Error(error.message);
    }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from(KV_TABLE).upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) {
        throw new Error(error.message);
    }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
    const supabase = client()
    const { data, error } = await supabase.from(KV_TABLE).select("value").in("key", keys);
    if (error) {
        throw new Error(error.message);
    }
    return data?.map((d: { value: any }) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
    const supabase = client()
    const { error } = await supabase.from(KV_TABLE).delete().in("key", keys);
    if (error) {
        throw new Error(error.message);
    }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
    const supabase = client()
    const { data, error } = await supabase.from(KV_TABLE).select("key, value").like("key", prefix + "%");
    if (error) {
        throw new Error(error.message);
    }
    return data?.map((d: { value: any }) => d.value) ?? [];
};

// List keys by prefix.
export const listKeys = async (prefix: string): Promise<string[]> => {
    const supabase = client()
    const { data, error } = await supabase.from(KV_TABLE).select("key").like("key", prefix + "%");
    if (error) {
        throw new Error(error.message);
    }
    return data?.map((d: { key: string }) => d.key) ?? [];
};
