/* AUTOGENERATED FILE - CLEARED FOR SECURITY */

// This file previously contained hardcoded credentials.
// All configuration is now strictly handled via .env and src/lib/supabase.ts

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";
