export const COPY = {
    common: {
        dateTime: "Date & Time",
        date: "Date",
        time: "Time",
        tags: "Tags",
        amount: "Amount",
        capital: "Capital",
        value: "Value",
        actions: {
            save: "Save",
            cancel: "Cancel",
            add: "Add",
            update: "Update",
            delete: "Delete",
            confirm: "Confirm",
            abort: "Cancel",
            execute: "Apply",
            back: "Back",
            next: "Next",
            record: "Record",
            clear: "Clear All Data",
            reset: "Reset Data",
            purge: "Clean Up",
        },
        status: {
            loading: "Loading...",
            success: "Success",
            failed: "Failed",
            offline: "Offline Mode",
            error: "Error",
        }
    },
    transactions: {
        addMoneyOut: "Add Expense",
        addMoneyIn: "Add Income",
        addDebt: "Add Debt",
        expenseLabel: "Expense",
        incomeLabel: "Income",
        debtLabel: "Debt",
        description: "Description",
        source: "Source",
        personName: "Person",
        account: "Account",
        category: "Category",
        tagsLabel: "Tags",
        recurring: "Recurring",
        recurringEntries: "Recurring entries",
        recurringDescription: "Recurring transaction",
        principalAmount: "Principal amount",
        interestRate: "Interest Rate",
        duration: "Duration",
        syncEmi: "Sync EMI to Transaction",
        syncYield: "Sync Yield to Transaction",
        limitWarning: "Credit Limit Warning",
        breachRisk: "Limit Breach Risk",
        justificationRequired: "Justification Required",
        aiSuggestion: "AI Suggested",
        quickFill: "Quick Fill",
        applySuggestion: "Apply Suggestion",
        repaymentDate: "Due Date",
        principalCapital: "Principal Amount",
        loanInvestmentDetails: "Loan/Investment Details",
        lentMoney: "I Lent Money",
        borrowedMoney: "I Borrowed Money",
        noAccounts: "No accounts found",
    },
    dashboard: {
        planTitle: "Your Finance Plan",
        overallHealth: "Overall Health",
        income: "Income",
        expenses: "Expenses",
        spendingTrend: "Spending Trend",
        topExpenses: "Major Expenses",
        billCommitments: "Upcoming Bills",
        safeToSpend: "Safe to Spend",
        reservedFunds: "Reserved for Goals",
        totalBalance: "Total Balance",
        protocolInterpretation: "Analysis",
        safeZoneHealth: "Safe Zone Health",
        actionFlow: "Action Flow",
        actionFlowEfficiency: "Action Flow Efficiency",
        burnTrend: "Burn Trend",
        highPowerNode: "High Power Node identified",
        dslBreakdown: "Daily Spending Limit Breakdown",
    },
    goals: {
        allocateTitle: "Allocate to Goal",
        reserveTitle: "Allocate to Emergency Fund",
        moveLiquidity: "Move money from account to",
        surplusFound: "Extra Savings Found",
        savingsGoal: "Savings Goal",
        emergencyFund: "Emergency Fund",
        completed: "Completed",
        remainingBalance: "Remaining Balance",
        moveFunds: "Move funds",
        allocationReady: "Ready to allocate funds",
    },
    aiAdvisor: {
        title: "AI Advisor",
        strategyTitle: "Strategic Recommendation",
        statusRecovery: "RECOVERY",
        statusGrowth: "GROWTH",
        nextMilestone: "Next Milestone",
        smartBalance: "Smart Balance",
        insightTitle: "Financial Insight",
        nextSteps: "Recommended Actions",
        suggestedActions: "Suggested Actions",
    },
    settings: {
        factoryReset: "Reset Data",
        wipeData: "Clear All Data",
        wipeDescription: "Clear all transactions and recurring entries (keeps account)",
        achievementLevel: "Achievement Level",
        achievementSelect: "Select an achievement to view details",
        achievementLocked: "Complete financial actions to unlock achievements",
        about: "About",
        subscriptionScanner: "Subscription Scanner",
        policyNumber: "Policy Number",
        createPolicy: "Create Policy",
        cleanupDuplicates: "Clean Up Duplicates",
    },
    notifications: {
        title: "Notifications",
        noNew: "No new notifications",
        clearNotifications: "notifications",
    },
    security: {
        securityCheck: "Security Check",
        securityEnabled: "Security Enabled",
        protectedBy: "Protected by FinHub Security",
    },
    achievements: {
        progress: "Achievement Progress",
        locked: "Locked",
        unlocked: "Achievement Unlocked",
    },
    transfers: {
        recordedInHistory: "This action is recorded in your transaction history",
        accountBalance: "balance of both accounts",
    },
    investments: {
        sellAll: "Sell All",
        valuation: "Valuation",
    },
    insurance: {
        safetyFeatures: "safety features",
        safetyPlans: "financial safety plans",
    },
    onboarding: {
        freedomScore: "Financial Freedom Score",
    }
};
